POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Unite Summit",
    "details": "Um evento para quem é apaixonado por programação.",
    "maximumAttendees": 100
}

###
POST http://localhost:3333/events/e8340e95-7afd-48c9-b099-3d44a2f7cb43/attendees
Content-Type: application/json

{
    "name": "Miguel A Ramos",
    "email": "miguel@teste.com"
}